### ISSUE TITLE
Scale is incorrect when window size is 360x360

### ISSUE THREAD

**Issue by redfood** [p5py/p5#98]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (if applicable)

**Expected behavior**

**Screenshots**

**System information:**
 - p5 release (version number or latest commit):
 - Python version:
 - Operating system:

**Additional context**

**Comment by vaishnavsm** [comment]
Could you check with the latest commit? I tried with the latest commit on Linux, and it gives the expected result(one fullscreen square).

**Comment by redfood** [comment]
Just tried it with the latest master.  Same issue.  Maybe it is mac specific?

**Comment by parsoyaarihant** [comment]
Its working perfectly on my machine. I too use a Mac (Mojave):
![Screenshot 2019-04-04 at 10 16 09 PM](https://user-images.githubusercontent.com/15258498/55573333-569d4800-5727-11e9-8808-b48d05db9370.png)

**Comment by redfood** [comment]
Hmm, maybe its High Sierra specific?  

It is a very odd error - what is magic about a size 360? (Although, that fact that it is 360 and not some other number makes me a bit suspicious -  some weird interaction with a hardcoded value used for angle conversion?)

**Comment by redfood** [comment]
I just noticed: p5/p5/sketch/userspace.py

Has the following:
```
builtins.width = 360
builtins.height = 360
```

Any chance my issue is related to this?

**Comment by abhikpal** [comment]
@redfood, those are just the default parameters that get used when `size()` is not called. We used to have this issue on the Mac sometime ago but it was fixed last summer or so. Could you double check if you're on the correct version of p5py?

**Comment by redfood** [comment]
I just ran `install p5 -U` and it said everything was up to date.  Just to double check I also downloaded the master from github and used it to replace my p5 in the `site-packages` directory.  I still have the issue.  Is there any way to get p5 to report which version is running?

**Comment by abhikpal** [comment]
> Is there any way to get p5 to report which version is running?

There is:
```python
>>> import p5
>>> print(p5.__version__)
```

But if you're downloaded the current version and had the same issue, it's possible that it's a p5py bug.

**Comment by redfood** [comment]
```
>>> import p5
>>> print(p5.__version__)
0.5.0
>>> 
```

**Comment by jeremydouglass** [comment]
> 1/4 of the window

I wonder if that could somehow be a pixelDensity-related issue.

Just to be clear, with size(361, 361) the display is normal?

**Comment by redfood** [comment]
> Just to be clear, with size(361, 361) the display is normal?

Yes- it works correctly with `size(361, 361)` 

(it even works correctly with `size(360, 361)` )

**Comment by pikeas** [comment]
Similar behavior on a 2019 Macbook Pro, which has a Retina screen. p5 0.6.0 (latest release), Python 3.7.4.

25% square in bottom left @ 360x360, full window square (minus the last line) @ 361x360 or 360x361.

**Comment by jeremydouglass** [comment]
I'm able to reproduce this on p5 version 0.6.0, 2016 MacBook Pro (retina), macOS 10.12.6

The broken layout happens 

1. on exactly `size(360,360)`. It won't happen on `size(359, 359)`, or `size(360 361)`.

```
from p5 import *

def setup():
    size(360,360)

def draw():
    background(0)
    rect((0,0),100,100)

if __name__ == '__main__':
    run()
```

2. OR, if you omit size / omit setup.

```
from p5 import *

def draw():
    background(0)
    rect((0,0),100,100)

if __name__ == '__main__':
    run()
```

Expected: a black sketch, with a 100x100 rect in the upper left. Here it is at 360x361:

<img width="360" alt="Screen Shot 2020-04-25 at 10 59 14 AM" src="https://user-images.githubusercontent.com/798570/80287023-e5d71e00-86e3-11ea-8589-cb7c4b18d065.png">

Instead, at 360x360 or with no size / no setup:

<img width="360" alt="Screen Shot 2020-04-25 at 10 57 43 AM" src="https://user-images.githubusercontent.com/798570/80286989-a1e41900-86e3-11ea-92a7-b9d5eafb488b.png">

**Comment by zaxusemk** [comment]
Sorry to necro this issue, but I'm seeing a similar issue on Linux. Was a solution ever found for this? If not, I'll set up a demo script to reproduce on my system and get the deets together.
